[package]
name = "astral"
version = "0.1.0"
authors = ["Vincent PALANCHER <vincent.palancher@gmail.com>"]
edition = "2018"

[dependencies]
amethyst = "0.11.0"

[features]
empty = ["amethyst/vulkan"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
